# Generated by Django 4.0.4 on 2022-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestoDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, default='profile2.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='picture',
            field=models.ImageField(blank=True, default='profile2.png', null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='plat',
            table='Plat',
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('num_tel', models.CharField(max_length=30)),
                ('rest_dislike', models.ManyToManyField(related_name='dislike', to='RestoDApp.client')),
                ('rest_like', models.ManyToManyField(related_name='like', to='RestoDApp.client')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('prix', models.FloatField()),
                ('category', models.ManyToManyField(related_name='item', to='RestoDApp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prix', models.FloatField()),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='RestoDApp.menuitem')),
            ],
        ),
    ]
