# Generated by Django 4.0.4 on 2022-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestoDApp', '0002_client_picture_partenaire_picture_alter_plat_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(related_name='liste_menu', to='RestoDApp.menuitem'),
        ),
    ]
