# Generated by Django 4.0.4 on 2022-05-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestoDApp', '0003_restaurant_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, related_name='liste_menu', to='RestoDApp.menuitem'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislike', to='RestoDApp.client'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rest_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to='RestoDApp.client'),
        ),
    ]
