# Generated by Django 4.0.4 on 2022-05-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestoDApp', '0006_remove_menuitem_category_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='resto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_proprietaire', to='RestoDApp.restaurant'),
        ),
        migrations.DeleteModel(
            name='Plat',
        ),
    ]
